# Site settings
title: VHA ORH Care-Share Pilot
email: project-care-share-list@lists.mitre.org
description: > # this means to ignore newlines until "baseurl:"
  Development of this pilot is sponsored by the Veterans Health Administration
  (VHA) Office of Rural Health (ORH).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://care-share.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  care-share

# Build settings
markdown: kramdown
